"""Application-wide constants."""

# Organization and application names for QSettings
ORGANIZATION_NAME = "Xian"
APPLICATION_NAME = "VideoGameTranslator"

# Model identifiers
MODEL_QWEN_9B = "Qwen/Qwen3.5-9B"
MODEL_QWEN_4B = "Qwen/Qwen3.5-4B"
MODEL_QWEN_2B = "Qwen/Qwen3.5-2B"
MODEL_TRANSLATEGEMMA_12B = "google/translategemma-12b-it"
MODEL_TRANSLATEGEMMA_4B = "google/translategemma-4b-it"

# VRAM thresholds (in GB)
VRAM_THRESHOLD_9B = 18
VRAM_THRESHOLD_4B = 10
VRAM_THRESHOLD_2B = 6
VRAM_THRESHOLD_TRANSLATEGEMMA_12B = 20
VRAM_THRESHOLD_TRANSLATEGEMMA_4B = 10
VRAM_AUTO_SELECT_9B = 20
VRAM_AUTO_SELECT_4B = 12
VRAM_AUTO_SELECT_2B = 8

# UI timing
API_CHECK_DEBOUNCE_MS = 1000
KEEP_ON_TOP_INTERVAL_MS = 2000
LOG_MAX_ENTRIES = 50
LOG_BLOCK_MAX_COUNT = 500
PULSE_HIGHLIGHT_DURATION_MS = 500

# Bubble geometry
BUBBLE_MIN_WIDTH = 100
BUBBLE_MIN_HEIGHT = 40
BUBBLE_MAX_COLLAPSED_WIDTH = 350
BUBBLE_MEASURE_MIN_WIDTH = 150
BUBBLE_EXPANDED_WIDTH = 400
BUBBLE_EXPANDED_HEIGHT = 250
BUBBLE_PADDING = 20
BUBBLE_BORDER_RADIUS = 10
BUBBLE_MARGIN = 8
BUBBLE_MAX_COUNT = 50
BUBBLE_DRAG_THRESHOLD = 5  # pixels to distinguish click from drag
BUBBLE_COORDINATE_SNAP_THRESHOLD = 5  # pixels for position change detection

# Overlap resolution
OVERLAP_RESOLUTION_MAX_ATTEMPTS = 80
OVERLAP_WRAP_MARGIN = 8

# Text processing
TRUNCATION_WORD_LIMIT = 8
MERGE_Y_DIFF_THRESHOLD = 20
MERGE_X_DIFF_MIN = -20
MERGE_X_DIFF_MAX = 40
MERGE_DUPLICATE_X_THRESHOLD = 50
CLUSTER_VERTICAL_PROXIMITY = 30
CLUSTER_HORIZONTAL_OVERLAP_MIN_RATIO = 0.3
APPEND_VERTICAL_GAP_MAX = 36
APPEND_HORIZONTAL_OVERLAP_MIN_RATIO = 0.3
IOU_MATCH_THRESHOLD = 0.4
CENTER_DISTANCE_THRESHOLD = 100
TEXT_MATCH_SCORE_BASE = 0.7
TEXT_MATCH_SCORE_MAX_DIST = 500

# Translation processing
WORKFLOW_TARGET_INTERVAL_MS = 1000
WORKFLOW_MIN_SLEEP_MS = 1
WORKFLOW_ERROR_SLEEP_MS = 1000
INFERENCE_TIMEOUT_SECONDS = 15.0
CPU_TIMEOUT_BASE_SECONDS = 180  # Base timeout for CPU inference
CPU_TIMEOUT_PER_TOKEN = 1.5  # Seconds per token budget (for ~1 tok/s on aarch64)

# Caching
IMAGE_CACHE_MAX_SIZE = 8
TRANSLATION_CACHE_MAX_SIZE = 16
DB_MAP_SIZE_BYTES = 1024 * 1024 * 1024  # 1GB

# Image processing
IMAGE_HASH_SIZE = 16  # 16x16 for perceptual hash
QWEN_MAX_DIMENSION = 1024
CPU_MAX_DIMENSION = 384  # Aggressive downscale for CPU — vision cost is O(n²) in pixels
TRANSLATEGEMMA_DIMENSION = 896

# Adaptive token limits for CPU based on image size
CPU_MAX_TOKENS_SMALL = 128   # Images < 256px: a few words/lines
CPU_MAX_TOKENS_MEDIUM = 192  # Images 256-400px: a paragraph
CPU_MAX_TOKENS_LARGE = 256   # Images > 400px: multiple paragraphs

# Style detection
STYLE_DETECT_CENTER_REGION = (0.25, 0.25, 0.5, 0.5)  # (x%, y%, w%, h%)
DEFAULT_FONT_FAMILY = "sans-serif"
DEFAULT_FONT_SIZE = 16.0

# Opacity
OPACITY_MIN = 30
OPACITY_MAX = 100
OPACITY_PANEL_MIN_ALPHA = 60
OPACITY_PANEL_MAX_ALPHA = 240
OPACITY_BORDER_MIN_ALPHA = 30
OPACITY_BORDER_MAX_ALPHA = 180
OPACITY_BUTTON_MIN_ALPHA = 80
OPACITY_BUTTON_MAX_ALPHA = 230
OPACITY_HOVER_EXTRA = 20
OPACITY_COMBO_MIN_ALPHA = 80
OPACITY_COMBO_MAX_ALPHA = 230

# Region selection
REGION_MIN_SIZE = 10  # minimum width/height for a valid region

# Settings defaults
DEFAULT_INTERVAL_MS = 2000
DEFAULT_OPACITY = 80
DEFAULT_REDACTION_MARGIN = 15
DEFAULT_REDACT_MARGIN_PANEL = 15
DEFAULT_THINKING_MODE = True
DEFAULT_MAX_TOKENS = 1024
DEFAULT_MODEL = "Qwen3.5-9B (Auto-select)"
DEFAULT_SOURCE_LANG = "auto"
DEFAULT_TARGET_LANG = "English"
DEFAULT_TRANSLATION_MODE = "full_screen"
DEFAULT_OCR_MODE = "ocr_translate"  # "ocr_only" or "ocr_translate"
DEFAULT_OUTPUT_MODE = "Overlay"  # "Overlay", "Clipboard", "File", "Overlay + Clipboard"
DEFAULT_MINIMIZE_ON_START = True
DEFAULT_DEBUG_MODE = False
DEFAULT_COMBINE_PARAGRAPHS = True
DEFAULT_SHOW_FULL_TEXT = True
DEFAULT_SHOW_LINK_ON_CLICK = False

# Redaction
REDACTION_DEFAULT_MARGIN = 15
